# Generated by Django 3.1.2 on 2020-10-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venture.property'),
        ),
    ]
