# Generated by Django 3.1.2 on 2020-10-15 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0003_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 20, 12, 53, 220599)),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
